import * as Logos from 'react-nba-logos';

const LogoComponents = {
	LogoATL: Logos.ATL,
	LogoBOS: Logos.BOS,
	LogoCHA: Logos.CHA,
	LogoCHI: Logos.CHI,
	LogoCLE: Logos.CLE,
	LogoDAL: Logos.DAL,
	LogoDEN: Logos.DEN,
	LogoDET: Logos.DET,
	LogoGSW: Logos.GSW,
	LogoHOU: Logos.HOU,
	LogoIND: Logos.IND,
	LogoLAC: Logos.LAC,
	LogoLAL: Logos.LAL,
	LogoMEM: Logos.MEM,
	LogoMIA: Logos.MIA,
	LogoMIL: Logos.MIL,
	LogoMIN: Logos.MIN,
	LogoNOP: Logos.NOP,
	LogoNYK: Logos.NYK,
	LogoBKN: Logos.BKN,
	LogoOKC: Logos.OKC,
	LogoORL: Logos.ORL,
	LogoPHI: Logos.PHI,
	LogoPHX: Logos.PHX,
	LogoPOR: Logos.POR,
	LogoSAC: Logos.SAC,
	LogoSAS: Logos.SAS,
	LogoTOR: Logos.TOR,
	LogoUTA: Logos.UTA,
	LogoWAS: Logos.WAS,
};

export default LogoComponents;
