import * as Logos from 'react-nba-logos';

const LogoComponents = {
	logoATL: Logos.ATL,
	logoBOS: Logos.BOS,
	logoCHA: Logos.CHA,
	logoCHI: Logos.CHI,
	logoCLE: Logos.CLE,
	logoDAL: Logos.DAL,
	logoDEN: Logos.DEN,
	logoDET: Logos.DET,
	logoGSW: Logos.GSW,
	logoHOU: Logos.HOU,
	logoIND: Logos.IND,
	logoLAC: Logos.LAC,
	logoLAL: Logos.LAL,
	logoMEM: Logos.MEM,
	logoMIA: Logos.MIA,
	logoMIL: Logos.MIL,
	logoMIN: Logos.MIN,
	logoNOP: Logos.NOP,
	logoNYK: Logos.NYK,
	logoBKN: Logos.BKN,
	logoOKC: Logos.OKC,
	logoORL: Logos.ORL,
	logoPHI: Logos.PHI,
	logoPHX: Logos.PHX,
	logoPOR: Logos.POR,
	logoSAC: Logos.SAC,
	logoSAS: Logos.SAS,
	logoTOR: Logos.TOR,
	logoUTA: Logos.UTA,
	logoWAS: Logos.WAS,
};

export default LogoComponents;
